name: docker-ci
on: [push, pull_request]

jobs:
  build:
    name: Build on haskell:${{ matrix.image_tag }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        image_tag: ['8.8.4', '8.10.2', '9.0.1']
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Cache docker builds
        uses: actions/cache@v2
        with:
          path: |
            ~/cache/cabal/packages
            ~/cache/cabal/store
            dist-newstyle
          key: docker-${{ runner.os }}-${{ matrix.image_tag }}
          restore-keys: |
            docker-${{ runner.os }}-

      - run: |
          mkdir -p ~/cache/cabal
          docker run -td --name builder -v ~/cache/cabal:/root/.cabal -v $(pwd):/srv -w /srv haskell:${{ matrix.image_tag }} bash
          docker exec builder bash -c "cabal v2-update"
          docker exec builder bash -c "cabal v2-configure -fno-avx --enable-tests --enable-benchmarks"

      - run: docker exec builder bash -c "cabal v2-build && cabal v2-test --test-show-details=direct"
      - run: docker exec builder bash -c "cabal check && cabal v2-haddock && cabal v2-sdist"
