on: [push, pull_request]
name: osx-ci
jobs:
  build:
    strategy:
      matrix:
        os: ['macos-10.15', 'macos-11']
        ghc: ['8.8', '8.10', '9.0']
        cabal: ['3.4']
    runs-on:  ${{ matrix.os }}
    name: Haskell GHC ${{ matrix.ghc }} sample
    env:
        CONFIG: "--enable-tests --enable-benchmarks"
    steps:
      - name: CPU info
        run: |
            sysctl -n machdep.cpu.brand_string
            sysctl -n machdep.cpu.features
            sysctl -n machdep.cpu.leaf7_features

      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        id: setup-haskell-cabal # <--- give it a name for later cache usage
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - run: |
          cabal update
          cabal freeze $CONFIG

      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-

      - run: |
          cabal configure $CONFIG
          cabal build $CONFIG
          cabal test --test-show-details=direct
      - run: |
          cabal haddock
          cabal check
          cabal sdist
