on: [push, pull_request]
name: ubuntu-ci
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ghc: ['9.2', '9.4', '9.6']
        cabal: ['3.8']
        avx_flag: ['', '-fuse-avx2']  # vm doesnt support avx512
        chenck_array_bound_flag: ['', '-fcheck-array-bound']  # vm doesnt support avx512
    name: Haskell GHC ${{ matrix.ghc }}
    env:
        CONFIG: "--enable-tests --enable-benchmarks"
    steps:

      - name: CPU info
        run: |
            sudo apt-get install cpuid
            cpuid

      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        id: setup-haskell-cabal # <--- give it a name for later cache usage
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - run: |
          cabal update
          cabal freeze ${{ matrix.avx_flag }} ${{ matrix.chenck_array_bound_flag }} $CONFIG

      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-

      - run: |
          cabal configure ${{ matrix.avx_flag }} ${{ matrix.chenck_array_bound_flag }} $CONFIG
          cabal build $CONFIG
      - run: |
          cabal test --test-show-details=direct
      - run: |
          cabal haddock
          cabal check
          cabal sdist
