on: [push, pull_request]
name: ubuntu-ci
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ghc: ['8.8', '8.10', '9.0']
        cabal: ['3.2', '3.4']
        avx_flag: ['', '-fno-avx']
        exclude:
          # GHC 9+ only works with cabal v3.4+
          - ghc: 9.0
            cabal: 3.2
    name: Haskell GHC ${{ matrix.ghc }} sample
    env:
        CONFIG: "--enable-tests --enable-benchmarks"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        id: setup-haskell-cabal # <--- give it a name for later cache usage
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - run: |
          cabal update
          cabal freeze ${{ matrix.avx_flag }} $CONFIG

      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-

      - run: |
          cabal configure ${{ matrix.avx_flag }} $CONFIG  
          cabal build $CONFIG
          cabal test --test-show-details=direct
      - run: |
          cabal haddock
          cabal check
          cabal sdist
